[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
dynamic = ["version"]
name = "taxidtools"
dependencies = [
    "mkdocstrings-python",
]
